<?php

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/app/Presentation/@layout.latte */
final class Template_ff60e1ff01 extends Latte\Runtime\Template
{
	public const Blocks = [
		'snippet' => ['flashes' => 'blockFlashes'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">

	<title>';
		if ($this->hasBlock('title')) /* pos 7:9 */ {
			$this->renderBlock('title', [], function ($s, $type) {
				$ʟ_fi = new LR\FilterInfo($type);
				return LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('stripHtml', $ʟ_fi, $s));
			}) /* pos 7:22 */;
			echo ' | ';
		}
		echo 'Moje Oči</title>

	<link rel="stylesheet" href="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 9:31 */;
		echo '/assets/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
	
	<link rel="icon" href="eye.svg" sizes="any" type="image/svg+xml">

	
	<script src="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 15:15 */;
		echo '/assets/formulare/formulare.js"></script>
	<script src="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 16:15 */;
		echo '/assets/bootstrap/js/bootstrap.min.js"></script>
	<script src="https://unpkg.com/nette-forms@3"></script>
</head>

<body>
	<header class="bg-primary text-light position-sticky top-0 py-3 mb-4 z-3">
		<div class="container d-flex justify-content-center align-items-center">
			<h1><a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Home:Home:default')) /* pos 23:11 */;
		echo '" class="text-light text-decoration-none"><i class="bi bi-eye"></i> Moje Oči</a></h1>
		</div>
	</header>

	<div';
		echo ' id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('flashes')), '"';
		echo ' class="container mt-3 z-3">';
		$this->renderBlock('flashes', [], null, 'snippet') /* pos 27:7 */;
		echo '</div>
	<main class="container my-4 d-flex flex-column align-items-center">
';
		if ($this->hasBlock('title')) /* pos 34:3 */ {
			echo '		<h2 class="text-center">';
			$this->renderBlock('title', [], 'html') /* pos 34:40 */;
			echo '</h2>';
		}
		echo "\n";
		$this->renderBlock('content', [], 'html') /* pos 35:3 */;
		echo '	</main>
</body>
<script src="https://unpkg.com/naja@2/dist/Naja.min.js"></script>

<script>
    document.addEventListener(\'DOMContentLoaded\', () => {
        naja.initialize();
    });
</script>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '28'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** n:snippet="flashes" on line 27 */
	public function blockFlashes(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('flashes', 'static') /* pos 27:7 */;
		try {
			echo "\n";
			foreach ($flashes as $flash) /* pos 28:8 */ {
				echo '		<div class="alert alert-';
				echo LR\HtmlHelpers::escapeAttr($flash->type === 'error' ? 'danger' : $flash->type) /* pos 28:58 */;
				echo ' alert-dismissible fade show shadow-sm text-center" role="alert">
			';
				echo LR\HtmlHelpers::escapeText($flash->message) /* pos 29:4 */;
				echo '
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Zavřít"></button>
		</div>
';

			}

			echo '	';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}
}
