<?php

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/app/Components/RegistrationForm/completeForm.latte */
final class Template_f5cdad43a9 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$form = $this->global->formsStack[] = $this->global->uiControl['form'] /* pos 1:1 */;
		Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 1:1 */;
		echo '
    <div class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('name', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 3:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('name', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 4:9 */;
		echo '
    </div>

    <div class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('address', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 8:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('address', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 9:9 */;
		echo '
    </div>

    <div class="mb-4">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('program_type', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 13:9 */;
		echo ' <br>
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('program_type', $this->global)->getControl() /* pos 14:9 */;
		echo '
    </div>

    <div id="snippet-email" class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('reservation_email', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 18:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('reservation_email', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 19:9 */;
		echo '
    </div>

    <div id="snippet-phone" class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('reservation_phone', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 23:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('reservation_phone', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 24:9 */;
		echo '
    </div>

    <div id="snippet-patients" class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('max_patients', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 28:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('max_patients', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 29:9 */;
		echo '
    </div>

    ';
		echo Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControl()->addAttributes(['class' => 'btn btn-success w-100 mt-3']) /* pos 32:5 */;
		echo "\n";
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 33:1 */;
	}
}
