<?php

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/app/Components/RegistrationForm/initForm.latte */
final class Template_446fe1f204 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$form = $this->global->formsStack[] = $this->global->uiControl['form'] /* pos 1:1 */;
		Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 1:1 */;
		echo "\n";
		if ($form->hasErrors()) /* pos 2:10 */ {
			echo '    <div class="alert alert-danger">
';
			foreach ($form->errors as $error) /* pos 3:12 */ {
				echo '        <p>';
				echo LR\HtmlHelpers::escapeText($error) /* pos 3:48 */;
				echo '</p>
';

			}

			echo '    </div>
';
		}
		echo '
    <div class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('ico', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 7:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('ico', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 8:9 */;
		echo "\n";
		ob_start(fn() => '');
		try {
			echo '        <span class="text-danger small">';
			ob_start();
			try {
				echo LR\HtmlHelpers::escapeText($form['ico']->error) /* pos 9:53 */;

			} finally {
				$ʟ_ifc[0] = rtrim(ob_get_flush()) === '';
			}
			echo '</span>
';

		} finally {
			if ($ʟ_ifc[0] ?? null) {
				ob_end_clean();

			} else {
				echo ob_get_clean();
			}
		}
		echo '    </div>

    <div class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('contact_person', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 13:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('contact_person', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 14:9 */;
		echo "\n";
		ob_start(fn() => '');
		try {
			echo '        <span class="text-danger small">';
			ob_start();
			try {
				echo LR\HtmlHelpers::escapeText($form['contact_person']->error) /* pos 15:53 */;

			} finally {
				$ʟ_ifc[1] = rtrim(ob_get_flush()) === '';
			}
			echo '</span>
';

		} finally {
			if ($ʟ_ifc[1] ?? null) {
				ob_end_clean();

			} else {
				echo ob_get_clean();
			}
		}
		echo '    </div>

    <div class="mb-3">
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('email', $this->global)->getLabel())?->addAttributes(['class' => 'form-label fw-bold']) /* pos 19:9 */;
		echo '
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('email', $this->global)->getControl()->addAttributes(['class' => 'form-control']) /* pos 20:9 */;
		echo "\n";
		ob_start(fn() => '');
		try {
			echo '        <span class="text-danger small">';
			ob_start();
			try {
				echo LR\HtmlHelpers::escapeText($form['email']->error) /* pos 21:53 */;

			} finally {
				$ʟ_ifc[2] = rtrim(ob_get_flush()) === '';
			}
			echo '</span>
';

		} finally {
			if ($ʟ_ifc[2] ?? null) {
				ob_end_clean();

			} else {
				echo ob_get_clean();
			}
		}
		echo '    </div>

    <div class="form-check mb-4">
        ';
		echo Nette\Bridges\FormsLatte\Runtime::item('is_authorized', $this->global)->getControl()->addAttributes(['class' => 'form-check-input']) /* pos 25:9 */;
		echo '
        ';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('is_authorized', $this->global)->getLabel())?->addAttributes(['class' => 'form-check-label']) /* pos 26:9 */;
		echo "\n";
		ob_start(fn() => '');
		try {
			echo '        <span class="text-danger d-block small">';
			ob_start();
			try {
				echo LR\HtmlHelpers::escapeText($form['is_authorized']->error) /* pos 27:61 */;

			} finally {
				$ʟ_ifc[3] = rtrim(ob_get_flush()) === '';
			}
			echo '</span>
';

		} finally {
			if ($ʟ_ifc[3] ?? null) {
				ob_end_clean();

			} else {
				echo ob_get_clean();
			}
		}
		echo '    </div>

    ';
		echo Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControl()->addAttributes(['class' => 'btn btn-primary w-100']) /* pos 30:5 */;
		echo "\n";
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 31:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['error' => '3'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
