<?php

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/app/Services/../Mails/verification.latte */
final class Template_456232faa9 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<html>
<head>
    <style>
        body { font-family: sans-serif; color: #333; }
        .btn { display: inline-block; padding: 10px 20px; background: #0056b3; color: white; text-decoration: none; border-radius: 5px; }
    </style>
</head>
<body>
    <h2>Dobrý den, ';
		echo LR\HtmlHelpers::escapeText($contactPerson) /* pos 9:21 */;
		echo ',</h2>
    <p>děkujeme za zahájení registrace vašeho zdravotního zařízení do sítě MOJE OČI.</p>
    <p>Pro dokončení registrace a vyplnění zbývajících údajů o firmě a výběru programu klikněte prosím na tlačítko níže:</p>
    <p><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($link)) /* pos 12:18 */;
		echo ' class="btn">Dokončit registraci</a></p>
    <p>Pokud tlačítko nefunguje, zkopírujte tento odkaz do prohlížeče:<br> ';
		echo LR\HtmlHelpers::escapeText($link) /* pos 13:82 */;
		echo '</p>
</body>
</html>';
	}
}
