<?php

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/app/Presentation/Registration/complete.latte */
final class Template_64dee9b48d extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 1:1 */;
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="mb-4">Dokončení registrace</h1>
            <p class="lead">Vyberte variantu programu a doplňte zbývající údaje.</p>

            <div class="card shadow-sm">
                <div class="card-body">
';
		$ʟ_tmp = $this->global->uiControl->getComponent('completeForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* pos 10:21 */;

		echo '                </div>
            </div>
        </div>
    </div>
</div>
';
	}
}
