<?php

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: /var/www/html/app/app/Presentation/Registration/default.latte */
final class Template_2835150f72 extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('title', get_defined_vars()) /* pos 1:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	/** {block title} on line 1 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Registrace zdravotního zařízení';
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <p class="lead">Vyplňte prosím IČO a kontaktní e-mail. Pošleme vám na něj odkaz pro pokračování.</p>
            <div class="card shadow-sm">
                <div class="card-body">
';
		$ʟ_tmp = $this->global->uiControl->getComponent('initForm');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* pos 9:21 */;

		echo '                </div>
            </div>
        </div>
    </div>
</div>
';
	}
}
